apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.user }}-{{ .Values.postfix }}-terraform
  namespace: {{ .Values.user }}
data:
  {{- range $key, $value := .Values.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}