apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.user }}-{{ .Values.postfix }}-terraform
  namespace: aws
  labels:
    app: {{ .Values.user }}-{{ .Values.postfix }}-terraform
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.user }}-{{ .Values.postfix }}-terraform
        imagePullPolicy: Always
        image: sabababoy/terraform
        workingDir: /terraform/aws/{{ .Values.resource }}
        command: ["/bin/sh", "-c"]
        {{- if eq .Values.type  "deploy" }}
        args: [
          "terraform init; terraform apply -auto-approve;"
        ]
        {{- end }}
        {{- if eq .Values.type "destroy" }}
        args: [
          "terraform init; terraform destroy -auto-approve;"
        ]
        {{- end }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: secret_key
        {{- range $key, $value := .Values.data }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.user }}-{{ $.Values.postfix }}-terraform
              key: {{ $key }}
        {{- end }}
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/os: linux