apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: global-applicationset-test
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/sabababoy/labondemand
      revision: HEAD
      directories:
      - path: services/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:  
      project: default
      source: 
        repoURL: https://github.com/sabababoy/labondemand.git
        targetRevision: HEAD
        path: 'services/{{path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd