apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: global-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/sabababoy/labondemand
      revision: HEAD
      directories:
      - path: services/*
  template:
    metadata:
      name: global-applicationset
      namespace: test
    spec:  
      project: default
      source: 
        repoURL: https://github.com/sabababoy/labondemand.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd