apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: global-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/sabababoy/labondemand
      revision: HEAD
      directories:
      - path: services/*
