apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.name }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  mysql-cluster.cnf: |
    [ndbd default]
    NoOfReplicas=2
    DataMemory=80M
    IndexMemory=18M


    [ndb_mgmd]
    NodeId=1
    hostname={{ .Values.user }}-ndb-mgmd.{{ .Values.user }}.svc.cluster.local
    datadir=/var/lib/mysql

    [ndbd]
    NodeId=2
    hostname={{ .Values.user }}-ndb-data-node.{{ .Values.user }}.svc.cluster.local
    datadir=/var/lib/mysql

    [ndbd]
    NodeId=3
    hostname={{ .Values.user }}-ndb-data-node.{{ .Values.user }}.svc.cluster.local
    datadir=/var/lib/mysql

    [mysqld]
    NodeId=4
    hostname={{ .Values.user }}-mysql-daemon.{{ .Values.user }}.svc.cluster.local

    [mysqld]
    NodeId=5
    hostname={{ .Values.user }}-mysql-daemon.{{ .Values.user }}.svc.cluster.local
