apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.name }}
data:
  config.cnf: |
    [NDBD DEFAULT]
    NoOfReplicas=2
    DataMemory=80M
    IndexMemory=18M

    [MYSQL DEFAULT]

    [NDB_MGMD DEFAULT]

    [TCP DEFAULT]

    [NDB MGMD]
    NodeId=1
    HostName={{ .Values.user }}-ndb-mgmd

    [NDBD]
    NodeId=2
    HostName={{ .Values.user }}-ndb-data-node

    [NDBD]
    NodeId=3
    HostName={{ .Values.user }}-ndb-data-node

    [MYSQLD]
    NodeId=4
    HostName=mysqld1

    [MYSQLD]
    NodeId=5
    HostName=mysqld2
    
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}