apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.name }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  mysql-cluster.cnf: |
    [ndbd default]
    NoOfReplicas=2
    DataMemory=80M
    IndexMemory=18M


    [ndb_mgmd]
    NodeId=1
    hostname=10.97.79.135
    datadir=/var/lib/mysql

    [ndbd]
    NodeId=2
    hostname=172.19.0.3
    datadir=/var/lib/mysql

    [ndbd]
    NodeId=3
    hostname=172.19.0.4
    datadir=/var/lib/mysql

    [mysqld]
    NodeId=4
    hostname=172.19.0.10

    [mysqld]
    NodeId=5
    hostname=172.19.0.9