apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.name }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  mysql-cluster.cnf: |
    [ndbd default]
    NoOfReplicas=2
    DataMemory=80M
    IndexMemory=18M

    [tcp default]
    AllowUnresolvedHostnames=1

    [ndb_mgmd]
    NodeId=1
    hostname=0.0.0.0
    datadir=/var/lib/mysql

    [ndbd]
    NodeId=2
    hostname={{ .Values.user }}-ndb-data-node-0.{{ .Values.user }}-ndb-data-node.{{ .Values.user }}.svc.cluster.local
    datadir=/var/lib/mysql

    [ndbd]
    NodeId=3
    hostname={{ .Values.user }}-ndb-data-node-1.{{ .Values.user }}-ndb-data-node.{{ .Values.user }}.svc.cluster.local
    datadir=/var/lib/mysql

    [mysqld]
    [mysqld]

