apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 1186
    targetPort: 1186
  - protocol: TCP
    port: 22
    targetPort: 22