apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}-{{ .Values.version }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.name }}-{{ .Values.version }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  mysql-cluster.cnf: |
    [ndbd default]
    NoOfReplicas=2
    DataMemory=80M
    IndexMemory=18M

    [tcp default]
    AllowUnresolvedHostnames=1

    [ndb_mgmd]
    NodeId=1
    hostname={{ .Values.user }}-ndb-mgmd-{{ .Values.version }}-0.{{ .Values.user }}-ndb-mgmd-{{ .Values.version }}.{{ .Values.user }}.svc.cluster.local
    PortNumber=1186

    [ndbd]
    NodeId=2
    hostname={{ .Values.user }}-ndb-data-node-{{ .Values.version }}-0.{{ .Values.user }}-ndb-data-node-{{ .Values.version }}.{{ .Values.user }}.svc.cluster.local
    ServerPort=1186

    [ndbd]
    NodeId=3
    hostname={{ .Values.user }}-ndb-data-node-{{ .Values.version }}-1.{{ .Values.user }}-ndb-data-node-{{ .Values.version }}.{{ .Values.user }}.svc.cluster.local
    ServerPort=1186

    [mysqld]
    NodeId=4
    hostname={{ .Values.user }}-mysql-daemon-{{ .Values.version }}-0.{{ .Values.user }}-mysql-daemon-{{ .Values.version }}.{{ .Values.user }}.svc.cluster.local

    [mysqld]
    NodeId=5
    hostname={{ .Values.user }}-mysql-daemon-{{ .Values.version }}-1.{{ .Values.user }}-mysql-daemon-{{ .Values.version }}.{{ .Values.user }}.svc.cluster.local
