apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}-{{ .Values.version }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-{{ .Values.version }}
spec:
  serviceName: {{ .Values.name }}-{{ .Values.version }}
  replicas: {{ .Values.replicaCount | default 1}}
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.version }}
    spec:
      containers:
      - name: {{ .Values.name }}-{{ .Values.version }}
        imagePullPolicy: IfNotPresent
        image: sabababoy/mysql-cluster:8.0
        command: ["/bin/sh", "-c"]
        args: [
          "ssh-keygen -A && /usr/sbin/sshd -D & /usr/sbin/ndb_mgmd -f /etc/mysql-cluster.cnf --nodaemon -v"
        ]
        ports:
        - name: ndb-mgmd
          containerPort: 1186
        - name: ssh
          containerPort: 22
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mysql-cluster.cnf
          subPath: mysql-cluster.cnf
        env:
        {{- range $key, $value := .Values.configmap.data }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.configmap.name }}
              key: {{ $key }}
        {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.configmap.name }}