apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.user }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.user }}-{{ .Values.postfix }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}