apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  serviceName: {{ .Values.name }}
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        imagePullPolicy: IfNotPresent
        image: mysql/mysql-cluster:latest
        args:
        - mysqld
        ports:
        - name: ndbd
          containerPort: 3306
        env:
        {{- range $key, $value := .Values.configmap.data }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.configmap.name }}
              key: {{ $key }}
        {{- end }}
      