# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: {{ .Values.namespace }}
#   name: gmsa-use-role
# rules:
# - apiGroups: ["windows.k8s.io"]
#   resources: ["gmsacredentialspecs"]
#   verbs: ["use"]
#   resourceNames: ["k8swindows"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: gmsa-use-rolebinding
#   namespace: {{ .Values.namespace }}
# subjects:
# - kind: ServiceAccount
#   name: default
#   namespace: {{ .Values.namespace }}
# roleRef:
#   kind: Role
#   name: gmsa-use-role
#   apiGroup: rbac.authorization.k8s.io