apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mysql-applicationset
spec:
  generators:
  - git:
      repoURL: https://github.com/sabababoy/labondemand
      revision: HEAD
      directories:
      - path: services/mysql/values/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:  
      project: default
      source: 
        repoURL: https://github.com/sabababoy/labondemand.git
        targetRevision: HEAD
        helm:
          valueFiles:
          - services/mysql/values/{{path.basename}}/*.yaml
          chart:
            git:
              repoURL: https://github.com/sabababoy/labondemand.git
              revision: HEAD
              path: global/services/mysql/templates
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd