apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount | default 1}}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        imagePullPolicy: Always
        image: sabababoy/oracledb:23.3.0.0
        command: ["/bin/sh", "-c"]
        args: [
          "ssh-keygen -A && /usr/sbin/sshd -D & /opt/oracle/runOracle.sh"
        ]
        ports:
        - containerPort: {{ .Values.port }}
        env:
        {{- range $key, $value := .Values.configmap.data }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.configmap.name }}
              key: {{ $key }}
        {{- end }}
      nodeSelector:
        kubernetes.io/os: linux