apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Values.version }}
  namespace: {{ .Values.namespace }}
spec:
  ClusterIp: None
  selector:
    app: {{ .Values.name }}-{{ .Values.version }}
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306