apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.user}}-{{ .Values.postfix }}
  namespace: {{ .Values.user }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.user}}-{{ .Values.postfix }}
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22