apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oracledb-manager
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: global/services/oracledb/*
        repoURL: 'https://github.com/sabababoy/labondemand'
        revision: HEAD
  template:
    metadata:
      name: 'oracledb-{{path.basename}}'
    spec:
      destination:
        namespace: argocd
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: 'https://github.com/sabababoy/labondemand.git'
        targetRevision: HEAD
        path: global/services/oracledb/{{path.basename}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true