apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.user }}-{{ .Values.postfix }}-terraform
  namespace: {{ .Values.user }}
data:
  {{- range $key, $value := .Values.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  var.tf: |
    variable "data_center" {
      default = "devcloud"
    }
    variable "cluster" {
      default = "fenrir"
    }
    variable "workload_datastore" {
      default = "vmstore"
    }
    variable "user" {
      default = "autodeploy.vmware@vsphere.local"
    }
    variable "password" {
      default = "Tol3r8t3now!"
    }
    variable "vsphere_server" {
        default = "10.198.1.13"
    }
    variable "vmname" {
        default = "midserver-{{ .Values.user }}"
    }
    variable "developer" {
      default = "{{ .Values.user }}"
    }

    variable "application-name" {
      default = "midserver-{{ .Values.user }}"
    }

    variable "instalation_script" {
      description = "MID SERVER SET UP"
      type = list(string)
      default = [
          "setx INSTANCE_URL '{{ .Values.instanceUrl }}'",
          "setx USERNAME '{{ .Values.username }}'",
          "setx PASSWORD '{{ .Values.password }}'",
          "setx MID_NAME '{{ .Values.midName }}'",
          "powershell.exe -File C:\\Installation Scripts\\midserver\\install.ps1 -Schedule"
          ]
    }