apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.user }}-{{ .Values.postfix }}-terraform
  namespace: {{ .Values.user }}
data:
  {{- range $key, $value := .Values.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  var.tf: |
    variable "data_center" {
      default = "devcloud"
    }
    variable "cluster" {
      default = "fenrir"
    }
    variable "workload_datastore" {
      default = "vmstore"
    }
    variable "user" {
      default = "autodeploy.vmware@vsphere.local"
    }
    variable "password" {
      default = "Tol3r8t3now!"
    }
    variable "vsphere_server" {
        default = "10.198.1.13"
    }
    variable "vmname" {
        default = "midserver"
    }
    variable "developer" {
      default = "{{ .Values.user }}"
    }
    variable "application-name" {
      default = "midserver-utah"
    }

    variable "instalation_script" {
      description = "MID SERVER SET UP"
      type = list(string)
      default = [
          "powershell.exe Write-Output 'SETTING UP MID SERVER'",
          "powershell.exe -File C:\\setupmidserver.ps1 -Schedule",
          "powershell.exe Write-Output 'MID SERVER CONFIGURED'",
          "powershell.exe Start-Process 'C:\\Servicenow\\mid\\agent\\start.bat' -WindowStyle Hidden"
          ]
    }