apiVersion: batch/v1
kind: Deployment
metadata:
  name: {{ .Values.user }}-{{ .Values.postfix }}-terraform
  namespace: {{ .Values.user}}
  labels:
    app: {{ .Values.user }}-{{ .Values.postfix }}-terraform
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.user }}-{{ .Values.postfix }}-terraform
        imagePullPolicy: Always
        image: sabababoy/terraform
        command: ["/bin/sh", "-c"]
        args: [
          "ping -t localhost"
        ]
        volumeMounts:
        - name: {{ .Values.user }}-{{ .Values.postfix }}-terraform-config-volume
          mountPath: "$HOME"
          subPath: var.tf
      volumes:
      - name: {{ .Values.user }}-{{ .Values.postfix }}-terraform-config-volume
        configMap:
          name: {{ .Values.user }}-{{ .Values.postfix }}-terraform
      restartPolicy: Never
        command: ["/bin/sh", "-c"]
      nodeSelector:
        kubernetes.io/os: linux