apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  serviceName: {{ .Values.name }}
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        imagePullPolicy: IfNotPresent
        image: sabababoy/mysql-cluster:8.0
        command: ["/bin/sh", "-c"]
        args: [
          "ssh-keygen -A && /usr/sbin/sshd -D & /usr/sbin/ndbd -c {{ .Values.user }}-ndb-mgmd-0.{{ .Values.user }}-ndb-mgmd.{{ .Values.user }}.svc.cluster.local --initial--nodaemon -v"
        ]
        ports:
        - name: ndbd
          containerPort: 2202
      