apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mysql-1.0-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: services/mysql/1.0/chart/values/*
        repoURL: 'https://github.com/sabababoy/labondemand'
        revision: HEAD
  template:
    metadata:
      name: 'mysql-{{path.basename}}'
    spec:
      destination:
        namespace: argocd
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: 'https://github.com/sabababoy/labondemand.git'
        targetRevision: HEAD
        path: services/mysql/1.0/chart
        helm:
          valueFiles:
            - 'values/{{path.basename}}/values.yaml'