apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: midservers-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: services/midservers/values/*
        repoURL: 'https://github.com/sabababoy/labondemand'
        revision: HEAD
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: argocd
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: 'https://github.com/sabababoy/labondemand.git'
        targetRevision: HEAD
        helm:
          chart:
            git:
              path: services/midservers/templates
              repoURL: 'https://github.com/sabababoy/labondemand.git'
              revision: HEAD
          valueFiles:
            - services/midservers/values/aleksandr.karmazin/*.yaml

