apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}-{{ .Values.version }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.name }}-{{ .Values.version }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  my.cnf: |
    [mysqld]
    user=mysql
    ndbcluster
    ndb-connectstring={{ .Values.user }}-ndb-mgmd-0.{{ .Values.user }}-ndb-mgmd.{{ .Values.user }}.svc.cluster.local
    datadir=/var/lib/mysql

    [mysql_cluster]
    ndb-connectstring={{ .Values.user }}-ndb-mgmd-0.{{ .Values.user }}-ndb-mgmd.{{ .Values.user }}.svc.cluster.local