apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        imagePullPolicy: Always
        image: sabababoy/mysql-cluster:8.0
        command: ["/bin/sh", "-c"]
        args: [
          "ssh-keygen -A && /usr/sbin/sshd -D & mysqld --initialized"
        ]
        ports:
        - name: ndbd
          containerPort: 3306
        volumeMounts:
        - name: config-volume
          mountPath: /etc/my.cnf
          subPath: my.cnf
        env:
        {{- range $key, $value := .Values.configmap.data }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.configmap.name }}
              key: {{ $key }}
        {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.configmap.name }}
      