apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace }}
spec:
  ClusterIp: None
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306